language: scala

scala:
  - 2.11.5

sudo: false

cache:
  directory:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

jdk:
  - openjdk7
  - oraclejdk8

script
  - sbt ++$TRAVIS_SCALA_VERSION test
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
